export interface DesignProfile {
  colors: {
    primary: string;
    primaryForeground: string;
    secondary: string;
    secondaryForeground: string;
    accent: string;
    accentForeground: string;
    surface: string;
    surfaceForeground: string;
    muted: string;
    mutedForeground: string;
  };
  typography: {
    heading: string;
    body: string;
  };
  borderRadius: number;
  density: "compact" | "comfortable" | "spacious";
}

const SANS = "Inter, system-ui, -apple-system, sans-serif";
const SERIF = "Georgia, 'Times New Roman', serif";
const MONO = "JetBrains Mono, 'Fira Code', monospace";
const MODERN = "'Plus Jakarta Sans', Inter, system-ui, sans-serif";
const SLAB = "'Roboto Slab', Georgia, serif";

const SECTORS: Record<string, DesignProfile> = {
  technology: {
    colors: { primary: "#2563eb", primaryForeground: "#ffffff", secondary: "#7c3aed", secondaryForeground: "#ffffff", accent: "#06b6d4", accentForeground: "#ffffff", surface: "#f8fafc", surfaceForeground: "#0f172a", muted: "#f1f5f9", mutedForeground: "#64748b" },
    typography: { heading: MODERN, body: SANS }, borderRadius: 8, density: "compact",
  },
  healthcare: {
    colors: { primary: "#0891b2", primaryForeground: "#ffffff", secondary: "#0d9488", secondaryForeground: "#ffffff", accent: "#2dd4bf", accentForeground: "#042f2e", surface: "#f0fdfa", surfaceForeground: "#134e4a", muted: "#ccfbf1", mutedForeground: "#5eead4" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 12, density: "comfortable",
  },
  finance: {
    colors: { primary: "#1e3a5f", primaryForeground: "#ffffff", secondary: "#0ea5e9", secondaryForeground: "#ffffff", accent: "#f59e0b", accentForeground: "#1e3a5f", surface: "#f8fafc", surfaceForeground: "#0f172a", muted: "#e2e8f0", mutedForeground: "#64748b" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 4, density: "compact",
  },
  legal: {
    colors: { primary: "#1e293b", primaryForeground: "#ffffff", secondary: "#475569", secondaryForeground: "#ffffff", accent: "#cbd5e1", accentForeground: "#1e293b", surface: "#ffffff", surfaceForeground: "#1e293b", muted: "#f1f5f9", mutedForeground: "#64748b" },
    typography: { heading: SERIF, body: SERIF }, borderRadius: 4, density: "compact",
  },
  education: {
    colors: { primary: "#6366f1", primaryForeground: "#ffffff", secondary: "#8b5cf6", secondaryForeground: "#ffffff", accent: "#f472b6", accentForeground: "#831843", surface: "#f5f3ff", surfaceForeground: "#312e81", muted: "#ede9fe", mutedForeground: "#7c3aed" },
    typography: { heading: SLAB, body: SANS }, borderRadius: 8, density: "comfortable",
  },
  ecommerce: {
    colors: { primary: "#e11d48", primaryForeground: "#ffffff", secondary: "#f97316", secondaryForeground: "#ffffff", accent: "#fbbf24", accentForeground: "#451a03", surface: "#fff1f2", surfaceForeground: "#881337", muted: "#ffe4e6", mutedForeground: "#fb7185" },
    typography: { heading: MODERN, body: SANS }, borderRadius: 6, density: "comfortable",
  },
  food: {
    colors: { primary: "#ea580c", primaryForeground: "#ffffff", secondary: "#d97706", secondaryForeground: "#ffffff", accent: "#fcd34d", accentForeground: "#78350f", surface: "#fff7ed", surfaceForeground: "#7c2d12", muted: "#ffedd5", mutedForeground: "#fdba74" },
    typography: { heading: SLAB, body: SANS }, borderRadius: 12, density: "spacious",
  },
  hospitality: {
    colors: { primary: "#b45309", primaryForeground: "#ffffff", secondary: "#d97706", secondaryForeground: "#ffffff", accent: "#fde68a", accentForeground: "#713f12", surface: "#fffbeb", surfaceForeground: "#78350f", muted: "#fef3c7", mutedForeground: "#d97706" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 8, density: "spacious",
  },
  realestate: {
    colors: { primary: "#0f766e", primaryForeground: "#ffffff", secondary: "#14b8a6", secondaryForeground: "#ffffff", accent: "#fbbf24", accentForeground: "#451a03", surface: "#f0fdfa", surfaceForeground: "#134e4a", muted: "#ccfbf1", mutedForeground: "#2dd4bf" },
    typography: { heading: SLAB, body: SANS }, borderRadius: 6, density: "comfortable",
  },
  creative: {
    colors: { primary: "#db2777", primaryForeground: "#ffffff", secondary: "#9333ea", secondaryForeground: "#ffffff", accent: "#f43f5e", accentForeground: "#ffffff", surface: "#fdf2f8", surfaceForeground: "#831843", muted: "#fce7f3", mutedForeground: "#f472b6" },
    typography: { heading: MODERN, body: SANS }, borderRadius: 12, density: "spacious",
  },
  media: {
    colors: { primary: "#dc2626", primaryForeground: "#ffffff", secondary: "#2563eb", secondaryForeground: "#ffffff", accent: "#facc15", accentForeground: "#422006", surface: "#fef2f2", surfaceForeground: "#7f1d1d", muted: "#fee2e2", mutedForeground: "#f87171" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 4, density: "compact",
  },
  consulting: {
    colors: { primary: "#4f46e5", primaryForeground: "#ffffff", secondary: "#7c3aed", secondaryForeground: "#ffffff", accent: "#a78bfa", accentForeground: "#1e1b4b", surface: "#f5f3ff", surfaceForeground: "#1e1b4b", muted: "#ede9fe", mutedForeground: "#8b5cf6" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 6, density: "compact",
  },
  manufacturing: {
    colors: { primary: "#1e40af", primaryForeground: "#ffffff", secondary: "#3b82f6", secondaryForeground: "#ffffff", accent: "#f59e0b", accentForeground: "#1e3a8a", surface: "#eff6ff", surfaceForeground: "#1e3a8a", muted: "#dbeafe", mutedForeground: "#60a5fa" },
    typography: { heading: SLAB, body: SANS }, borderRadius: 4, density: "compact",
  },
  nonprofit: {
    colors: { primary: "#059669", primaryForeground: "#ffffff", secondary: "#10b981", secondaryForeground: "#ffffff", accent: "#fbbf24", accentForeground: "#064e3b", surface: "#ecfdf5", surfaceForeground: "#064e3b", muted: "#d1fae5", mutedForeground: "#34d399" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 8, density: "comfortable",
  },
  wellness: {
    colors: { primary: "#7c2d12", primaryForeground: "#ffffff", secondary: "#a16207", secondaryForeground: "#ffffff", accent: "#84cc16", accentForeground: "#1a2e05", surface: "#fefce8", surfaceForeground: "#422006", muted: "#fef9c3", mutedForeground: "#ca8a04" },
    typography: { heading: SERIF, body: SANS }, borderRadius: 12, density: "spacious",
  },
  saas: {
    colors: { primary: "#7c3aed", primaryForeground: "#ffffff", secondary: "#2563eb", secondaryForeground: "#ffffff", accent: "#06b6d4", accentForeground: "#083344", surface: "#f5f3ff", surfaceForeground: "#1e1b4b", muted: "#ede9fe", mutedForeground: "#a78bfa" },
    typography: { heading: MODERN, body: SANS }, borderRadius: 8, density: "compact",
  },
  transportation: {
    colors: { primary: "#0369a1", primaryForeground: "#ffffff", secondary: "#0c4a6e", secondaryForeground: "#ffffff", accent: "#f59e0b", accentForeground: "#451a03", surface: "#f0f9ff", surfaceForeground: "#0c4a6e", muted: "#e0f2fe", mutedForeground: "#7dd3fc" },
    typography: { heading: SANS, body: SANS }, borderRadius: 4, density: "compact",
  },
  energy: {
    colors: { primary: "#166534", primaryForeground: "#ffffff", secondary: "#15803d", secondaryForeground: "#ffffff", accent: "#facc15", accentForeground: "#422006", surface: "#f0fdf4", surfaceForeground: "#14532d", muted: "#dcfce7", mutedForeground: "#4ade80" },
    typography: { heading: SLAB, body: SANS }, borderRadius: 4, density: "compact",
  },
  retail: {
    colors: { primary: "#be123c", primaryForeground: "#ffffff", secondary: "#db2777", secondaryForeground: "#ffffff", accent: "#fbbf24", accentForeground: "#451a03", surface: "#fff1f2", surfaceForeground: "#881337", muted: "#ffe4e6", mutedForeground: "#fb7185" },
    typography: { heading: MODERN, body: SANS }, borderRadius: 6, density: "comfortable",
  },
  construction: {
    colors: { primary: "#92400e", primaryForeground: "#ffffff", secondary: "#b45309", secondaryForeground: "#ffffff", accent: "#f59e0b", accentForeground: "#451a03", surface: "#fffbeb", surfaceForeground: "#78350f", muted: "#fef3c7", mutedForeground: "#d97706" },
    typography: { heading: SLAB, body: SANS }, borderRadius: 4, density: "compact",
  },
};

const DEFAULT_PROFILE: DesignProfile = {
  colors: { primary: "#0070c4", primaryForeground: "#ffffff", secondary: "#6b7280", secondaryForeground: "#ffffff", accent: "#0ea5e9", accentForeground: "#ffffff", surface: "#f8f9fa", surfaceForeground: "#212529", muted: "#e9ecef", mutedForeground: "#868e96" },
  typography: { heading: SANS, body: SANS }, borderRadius: 8, density: "comfortable",
};

const INDUSTRY_SECTOR_MAP: Record<string, string> = {
  "software": "technology",
  "saas": "saas",
  "technology": "technology",
  "tech": "technology",
  "information-technology": "technology",
  "it-services": "technology",
  "computer-software": "technology",
  "cybersecurity": "technology",
  "cloud-computing": "technology",
  "artificial-intelligence": "technology",
  "machine-learning": "technology",
  "data-analytics": "technology",
  "blockchain": "technology",
  "internet": "technology",
  "telecommunications": "technology",
  "semiconductors": "technology",
  "hardware": "technology",
  "healthcare": "healthcare",
  "hospital": "healthcare",
  "medical": "healthcare",
  "pharmaceutical": "healthcare",
  "biotechnology": "healthcare",
  "dental": "healthcare",
  "mental-health": "wellness",
  "wellness": "wellness",
  "fitness": "wellness",
  "nutrition": "wellness",
  "yoga": "wellness",
  "meditation": "wellness",
  "spa": "wellness",
  "banking": "finance",
  "finance": "finance",
  "financial-services": "finance",
  "insurance": "finance",
  "accounting": "finance",
  "investment": "finance",
  "wealth-management": "finance",
  "mortgage": "finance",
  "credit-union": "finance",
  "fintech": "finance",
  "legal": "legal",
  "law-firm": "legal",
  "attorney": "legal",
  "law-practice": "legal",
  "notary": "legal",
  "paralegal": "legal",
  "education": "education",
  "school": "education",
  "university": "education",
  "college": "education",
  "training": "education",
  "tutoring": "education",
  "online-learning": "education",
  "elearning": "education",
  "preschool": "education",
  "childcare": "education",
  "vocational": "education",
  "ecommerce": "ecommerce",
  "retail": "retail",
  "clothing": "retail",
  "fashion": "retail",
  "apparel": "retail",
  "jewelry": "retail",
  "footwear": "retail",
  "beauty": "retail",
  "cosmetics": "retail",
  "skincare": "retail",
  "home-goods": "retail",
  "furniture": "retail",
  "electronics": "retail",
  "consumer-electronics": "retail",
  "books": "retail",
  "toys": "retail",
  "sports-equipment": "retail",
  "pet-supplies": "retail",
  "groceries": "food",
  "food-beverage": "food",
  "restaurant": "food",
  "catering": "food",
  "bakery": "food",
  "coffee-shop": "food",
  "brewery": "food",
  "winery": "food",
  "food-delivery": "food",
  "meal-prep": "food",
  "food-manufacturing": "food",
  "hospitality": "hospitality",
  "hotel": "hospitality",
  "resort": "hospitality",
  "lodging": "hospitality",
  "travel": "hospitality",
  "tourism": "hospitality",
  "event-planning": "hospitality",
  "venue": "hospitality",
  "nightlife": "hospitality",
  "entertainment": "media",
  "media": "media",
  "publishing": "media",
  "news": "media",
  "broadcasting": "media",
  "film": "media",
  "music": "media",
  "podcast": "media",
  "advertising": "creative",
  "marketing-agency": "creative",
  "creative-agency": "creative",
  "design": "creative",
  "graphic-design": "creative",
  "web-design": "creative",
  "photography": "creative",
  "videography": "creative",
  "animation": "creative",
  "architecture": "creative",
  "interior-design": "creative",
  "fashion-design": "creative",
  "consulting": "consulting",
  "management-consulting": "consulting",
  "business-consulting": "consulting",
  "hr-consulting": "consulting",
  "strategy": "consulting",
  "real-estate": "realestate",
  "property-management": "realestate",
  "real-estate-development": "realestate",
  "realty": "realestate",
  "commercial-real-estate": "realestate",
  "residential-real-estate": "realestate",
  "manufacturing": "manufacturing",
  "industrial": "manufacturing",
  "factory": "manufacturing",
  "warehousing": "manufacturing",
  "logistics": "transportation",
  "transportation": "transportation",
  "shipping": "transportation",
  "delivery": "transportation",
  "courier": "transportation",
  "freight": "transportation",
  "aviation": "transportation",
  "automotive": "transportation",
  "marine": "transportation",
  "rail": "transportation",
  "energy": "energy",
  "oil-gas": "energy",
  "renewable-energy": "energy",
  "solar": "energy",
  "wind-energy": "energy",
  "utilities": "energy",
  "mining": "energy",
  "construction": "construction",
  "contractor": "construction",
  "home-improvement": "construction",
  "remodeling": "construction",
  "landscaping": "construction",
  "roofing": "construction",
  "plumbing": "construction",
  "electrical": "construction",
  "hvac": "construction",
  "painting": "construction",
  "cleaning": "construction",
  "nonprofit": "nonprofit",
  "charity": "nonprofit",
  "foundation": "nonprofit",
  "ngo": "nonprofit",
  "social-services": "nonprofit",
  "religious": "nonprofit",
  "community-organization": "nonprofit",
  "government": "nonprofit",
  "public-sector": "nonprofit",
  "agriculture": "manufacturing",
  "farming": "manufacturing",
  "fishery": "manufacturing",
  "forestry": "manufacturing",
  "veterinary": "healthcare",
  "pet-care": "retail",
  "grooming": "retail",
  "dentist": "healthcare",
  "chiropractor": "healthcare",
  "physical-therapy": "healthcare",
  "optometry": "healthcare",
  "pharmacy": "healthcare",
  "medical-device": "healthcare",
  "home-healthcare": "healthcare",
  "senior-care": "healthcare",
  "insurance-broker": "finance",
  "real-estate-agent": "realestate",
  "property-investment": "realestate",
  "moving": "transportation",
  "storage": "transportation",
  "printing": "manufacturing",
  "signage": "manufacturing",
  "packaging": "manufacturing",
  "security": "technology",
  "pest-control": "construction",
  "junk-removal": "construction",
  "window-cleaning": "construction",
  "carpet-cleaning": "construction",
  "pool-service": "construction",
  "landlord": "realestate",
  "hvac-service": "construction",
  "plumber": "construction",
  "electrician": "construction",
  "roofer": "construction",
  "general-contractor": "construction",
  "daycare": "education",
  "preschool-childcare": "education",
  "tutor": "education",
  "music-lessons": "education",
  "art-school": "education",
  "dance-studio": "wellness",
  "martial-arts": "wellness",
  "personal-trainer": "wellness",
  "gym": "wellness",
  "crossfit": "wellness",
  "pilates": "wellness",
  "massage": "wellness",
  "acupuncture": "wellness",
  "meditation-center": "wellness",
  "counseling": "wellness",
  "therapy": "wellness",
  "life-coach": "consulting",
  "business-coach": "consulting",
  "career-coach": "consulting",
  "virtual-assistant": "technology",
  "bookkeeping": "finance",
  "tax-preparation": "finance",
  "payroll": "finance",
  "cpa": "finance",
  "financial-advisor": "finance",
  "estate-planning": "legal",
  "immigration-law": "legal",
  "family-law": "legal",
  "criminal-defense": "legal",
  "personal-injury": "legal",
  "real-estate-law": "legal",
  "corporate-law": "legal",
  "intellectual-property": "legal",
  "dentistry": "healthcare",
  "orthodontist": "healthcare",
  "periodontist": "healthcare",
  "oral-surgery": "healthcare",
  "pediatric-dentistry": "healthcare",
  "cosmetic-dentistry": "healthcare",
  "endodontist": "healthcare",
  "optometrist": "healthcare",
  "ophthalmology": "healthcare",
  "audiology": "healthcare",
  "speech-therapy": "healthcare",
  "occupational-therapy": "healthcare",
  "podiatrist": "healthcare",
  "urgent-care": "healthcare",
  "pediatrics": "healthcare",
  "dermatology": "healthcare",
  "cardiology": "healthcare",
  "orthopedics": "healthcare",
  "neurology": "healthcare",
  "psychiatry": "healthcare",
  "radiology": "healthcare",
  "surgery": "healthcare",
  "anesthesiology": "healthcare",
  "pathology": "healthcare",
  "obgyn": "healthcare",
  "oncology": "healthcare",
  "gastroenterology": "healthcare",
  "urology": "healthcare",
  "nephrology": "healthcare",
  "pulmonology": "healthcare",
  "endocrinology": "healthcare",
  "rheumatology": "healthcare",
  "allergy-immunology": "healthcare",
  "infectious-disease": "healthcare",
  "emergency-medicine": "healthcare",
  "family-medicine": "healthcare",
  "internal-medicine": "healthcare",
  "preventive-medicine": "healthcare",
  "sports-medicine": "healthcare",
  "pain-management": "healthcare",
  "addiction-medicine": "healthcare",
  "sleep-medicine": "healthcare",
  "genetics": "healthcare",
  "telemedicine": "healthcare",
  "concierge-medicine": "healthcare",
  "functional-medicine": "healthcare",
  "integrative-medicine": "healthcare",
  "naturopathy": "wellness",
  "homeopathy": "wellness",
  "chiropractic": "healthcare",
  "physical-medicine": "healthcare",
  "rehabilitation": "healthcare",
  "skilled-nursing": "healthcare",
  "assisted-living": "healthcare",
  "home-care": "healthcare",
  "hospice": "healthcare",
  "adult-day-care": "healthcare",
  "respite-care": "healthcare",
  "durable-medical-equipment": "healthcare",
  "medical-billing": "healthcare",
  "medical-coding": "healthcare",
  "health-information": "healthcare",
  "clinical-research": "healthcare",
  "clinical-trial": "healthcare",
  "regulatory-affairs": "healthcare",
  "medical-writing": "healthcare",
  "medical-transcription": "healthcare",
  "medical-education": "healthcare",
  "healthcare-consulting": "consulting",
  "healthcare-it": "technology",
  "healthcare-analytics": "technology",
  "population-health": "healthcare",
  "public-health": "nonprofit",
  "epidemiology": "healthcare",
  "biostatistics": "healthcare",
  "bioinformatics": "technology",
  "computational-biology": "technology",
  "structural-biology": "healthcare",
  "medicinal-chemistry": "healthcare",
  "drug-discovery": "healthcare",
  "drug-development": "healthcare",
  "regulatory-drug-device": "healthcare",
  "quality-assurance": "manufacturing",
  "quality-control": "manufacturing",
  "process-engineering": "manufacturing",
  "industrial-engineering": "manufacturing",
  "mechanical-engineering": "manufacturing",
  "electrical-engineering": "technology",
  "civil-engineering": "construction",
  "chemical-engineering": "manufacturing",
  "environmental-engineering": "energy",
  "biomedical-engineering": "healthcare",
  "aerospace-engineering": "manufacturing",
  "automotive-engineering": "transportation",
  "software-engineering": "technology",
  "data-engineering": "technology",
  "devops": "technology",
  "site-reliability": "technology",
  "platform-engineering": "technology",
  "infrastructure": "technology",
  "network-engineering": "technology",
  "security-engineering": "technology",
  "ml-engineering": "technology",
  "ai-engineering": "technology",
};

export function getDesignProfile(industrySlug: string | null | undefined): DesignProfile {
  if (!industrySlug) return DEFAULT_PROFILE;
  const sector = INDUSTRY_SECTOR_MAP[industrySlug.toLowerCase()];
  if (!sector) return DEFAULT_PROFILE;
  return SECTORS[sector] || DEFAULT_PROFILE;
}

export function profileToCssVariables(profile: DesignProfile): Record<string, string> {
  return {
    "--clr-primary": profile.colors.primary,
    "--clr-primary-foreground": profile.colors.primaryForeground,
    "--clr-secondary": profile.colors.secondary,
    "--clr-secondary-foreground": profile.colors.secondaryForeground,
    "--clr-accent": profile.colors.accent,
    "--clr-accent-foreground": profile.colors.accentForeground,
    "--clr-surface": profile.colors.surface,
    "--clr-surface-foreground": profile.colors.surfaceForeground,
    "--clr-muted": profile.colors.muted,
    "--clr-muted-foreground": profile.colors.mutedForeground,
    "--ff-heading": `"${profile.typography.heading.split(",")[0]?.trim()}", ${profile.typography.heading}`,
    "--ff-body": profile.typography.body,
    "--radius": `${profile.borderRadius}px`,
    "--density": profile.density,
    "--spacing-unit": profile.density === "compact" ? "0.25rem" : profile.density === "spacious" ? "0.5rem" : "0.375rem",
  };
}

export function applyDesignProfile(profile: DesignProfile): void {
  const vars = profileToCssVariables(profile);
  const root = document.documentElement;
  Object.entries(vars).forEach(([key, value]) => {
    root.style.setProperty(key, value);
  });
}
